name: tomcat
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.12.12=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  # 以下是适配Python 3.8的pip依赖（删除了错误的clip==1.0，降级了不兼容包）
  - pip:
    - absl-py==2.1.0
    - accelerate==0.28.0  # 降级：0.29+要求Python≥3.9
    - addict==2.4.0
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - aliyun-python-sdk-core==2.15.1
    - aliyun-python-sdk-kms==2.16.2
    - altair==4.2.2  # 降级：5.x要求Python≥3.9
    - annotated-types==0.5.0  # 降级：0.6+要求Python≥3.9
    - antlr4-python3-runtime==4.9.3
    - anyio==3.7.1  # 降级：4.x要求Python≥3.9
    - ase==3.21.1
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==23.2.0
    - backcall==0.2.0
    - bitarray==2.9.2
    - bleach==6.1.0
    - blinker==1.8.2
    - blis==0.7.11
    - braceexpand==0.1.7
    - brotli==1.1.0
    - cached-property==1.5.2
    - cachetools==5.3.3
    - catalogue==2.0.10
    - certifi==2024.2.2
    - cffi==1.16.0
    - cfgv==3.4.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cloudpathlib==0.18.1
    - colorama==0.4.6
    - comet-ml==3.33.6
    - conda-pack==0.8.0
    - confection==0.1.5
    - configobj==5.0.8
    - configparser==5.0.2
    - contexttimer==0.3.3
    - crcmod==1.7
    - cryptography==41.0.7  # 降级：42+要求Python≥3.9
    - cycler==0.10.0
    - cymem==2.0.8
    - cython==3.0.10
    - dataclasses==0.6
    - datasets==1.11.0
    - decorator==4.4.2
    - decord==0.6.0
    - dill==0.3.7
    - distlib==0.3.8
    - distro==1.9.0
    - docker-pycreds==0.4.0
    - dulwich==0.21.7
    - editdistance==0.8.1
    - einops==0.7.0
    - einops-exts==0.0.4
    - en-core-web-lg==3.7.1
    - everett==3.1.0
    - exceptiongroup==1.1.3  # 降级：1.2+要求Python≥3.9
    - executing==2.0.1
    - fairscale==0.4.4
    - fairseq==0.10.0
    - filelock==3.13.1
    - flash-attn==0.2.7
    - frozenlist==1.4.1
    - fsspec==2023.10.0
    - ftfy==6.1.3
    - g4f==0.3.2.1
    - gast==0.5.4
    - git-lfs==1.6
    - gitdb==4.0.7
    - gitpython==3.1.30
    - google-auth==2.29.0
    - google-auth-oauthlib==1.0.0
    - googledrivedownloader==0.4
    - grpcio==1.62.2
    - h11==0.14.0
    - h5py==3.1.0
    - httpcore==0.17.3  # 降级：1.x要求Python≥3.9
    - httpx==0.24.1  # 降级：0.27+要求Python≥3.9
    - huggingface-hub==0.23.4
    - hydra-core==1.3.2
    - identify==2.5.36
    - idna==3.6
    - imagehash==4.3.1
    - imageio==2.34.1
    - importlib-metadata==6.8.0  # 降级：7.x要求Python≥3.9
    - importlib-resources==5.12.0  # 降级：6.x要求Python≥3.9
    - iopath==0.1.10
    - ipython==8.12.3
    - isodate==0.6.0
    - jedi==0.19.1
    - jinja2==3.0.1
    - jmespath==0.10.0
    - joblib==1.4.0
    - jsonschema==4.19.2  # 降级：4.21+要求Python≥3.9
    - jsonschema-specifications==2023.7.1  # 降级：适配jsonschema 4.19
    - kaggle==1.6.14
    - kiwisolver==1.3.1
    - langcodes==3.4.0
    - language-data==1.2.0
    - littleutils==0.2.2
    - llvmlite==0.36.0
    - lxml==5.2.1
    - marisa-trie==1.2.0
    - markdown==3.6
    - markdown-it-py==3.0.0
    - markupsafe==2.0.1
    - matplotlib==3.3.4
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - modelscope==1.14.0
    - msgpack==1.0.8
    - multidict==6.0.5
    - multiprocess==0.70.15
    - murmurhash==1.0.10
    - networkx==2.5.1
    - nodeenv==1.9.1
    - numba==0.53.1
    - numpy==1.24.4
    - oauthlib==3.2.2
    - ogb==1.3.1
    - omegaconf==2.3.0
    - open-clip-torch==2.26.1  # 保留正确的CLIP包
    - openai==1.10.0  # 降级：1.16+要求Python≥3.9
    - opencv-python-headless==4.5.5.64
    - opendatasets==0.1.22
    - oss2==2.18.5
    - outdated==0.2.1
    - packaging==24.0
    - pandas==1.4.2
    - parso==0.8.4
    - pathtools==0.1.2
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pillow==10.2.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.2.1
    - plotly==5.22.0
    - portalocker==2.8.2
    - pre-commit==3.5.0
    - preshed==3.0.9
    - progressbar==2.5
    - promise==2.3
    - prompt-toolkit==3.0.47
    - protobuf==3.20.0
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==16.0.0
    - pyarrow-hotfix==0.6
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pycocoevalcap==1.2
    - pycocotools==2.0.7
    - pycparser==2.22
    - pycryptodome==3.20.0
    - pydantic==1.10.14  # 降级：2.x要求Python≥3.9
    - pydantic-core==2.18.1
    - pydeck==0.9.1
    - pygments==2.17.2
    - pyparsing==2.4.7
    - python-box==6.1.0
    - python-dateutil==2.9.0.post0
    - python-louvain==0.15
    - python-magic==0.4.27
    - python-slugify==8.0.4
    - pytz==2024.1
    - pywavelets==1.4.1
    - pyyaml==5.4.1
    - ray==2.10.0
    - rdflib==5.0.0
    - referencing==0.30.2  # 降级：适配jsonschema 4.19
    - regex==2023.12.25
    - requests==2.31.0
    - requests-oauthlib==2.0.0
    - requests-toolbelt==1.0.0
    - rich==13.7.1
    - rpds-py==0.10.6  # 降级：适配jsonschema 4.19
    - rsa==4.9
    - sacrebleu==2.4.2
    - sacremoses==0.1.1
    - safetensors==0.4.3
    - salesforce-lavis==1.0.2
    - scikit-image==0.19.3
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - semantic-version==2.10.0
    - sentencepiece==0.2.0
    - sentry-sdk==1.14.0
    - shellingham==1.5.4
    - shortuuid==1.0.1
    - simplejson==3.19.2
    - six==1.16.0
    - sklearn==0.0
    - smart-open==7.0.4
    - smmap==4.0.0
    - sniffio==1.3.1
    - sortedcontainers==2.4.0
    - spacy==3.7.5
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - srsly==2.4.8
    - stack-data==0.6.3
    - streamlit==1.32.2  # 降级：1.36+要求Python≥3.9
    - subprocess32==3.5.4
    - tabulate==0.9.0
    - tenacity==8.4.2
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.2.2
    - text-unidecode==1.3
    - thinc==8.2.5
    - threadpoolctl==3.4.0
    - tifffile==2023.7.10
    - timm==0.4.12
    - tokenizers==0.15.2
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.12.1
    - torch==1.11.0+cu113
    - torch-geometric==1.7.0
    - torchvision==0.12.0+cu113
    - tornado==6.4.1
    - tqdm==4.66.2
    - traitlets==5.14.3
    - transformers==4.35.2
    - typer==0.9.0  # 降级：0.12+要求Python≥3.9
    - typing-extensions==4.10.0
    - urllib3==2.2.1
    - virtualenv==20.26.3
    - wandb==0.10.30
    - wasabi==1.1.3
    - watchdog==4.0.1
    - wcwidth==0.2.13
    - weasel==0.4.1
    - webdataset==0.2.86
    - webencodings==0.5.1
    - websocket-client==1.3.3
    - werkzeug==2.1.2
    - wilds==1.1.0
    - wrapt==1.16.0
    - wurlitzer==3.0.3
    - xxhash==3.4.1
    - yapf==0.40.2
    - yarl==1.9.4
    - zipp==3.16.2  # 降级：适配importlib-metadata 6.8